version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: twitcord_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./twitcord_Back/.envs/.production/.django
      - ./twitcord_Back/.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: twitcord_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./twitcord_Back/.envs/.production/.postgres

  redis:
    image: redis:5.0


