export const ActionTypes = {
  SET_SIGN_UP_INFO: 'SET_SIGN_UP_INFO',
  SET_LOG_IN_INFO: 'SET_LOG_IN_INFO',
  SET_TWEET_TEXT: 'SET_TWEET_TEXT',
  SET_SNACKBAR_STATE: 'SET_SNACKBAR_STATE',
  SET_USER_SEARCH_RESULT: 'SET_USER_SEARCH_RESULT',
  SET_TWEET_SEARCH_RESULT: 'SET_TWEET_SEARCH_RESULT',
  SET_PROFILE_INFO: 'SET_PROFILE_INFO',
  SET_USER_GENERAL_INFO: 'SET_USER_GENERAL_INFO',
  SET_FOLLOW_COUNT: 'SET_FOLLOW_COUNT',
  SET_SIDE_DRAWER_ENABLE: 'SET_SIDE_DRAWER_ENABLE',
  SET_SEARCH_INPUT: 'SET_SEARCH_INPUT',
};

