# Generated by Django 3.1.7 on 2021-04-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitcord_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitcorduser',
            name='bio',
            field=models.TextField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='twitcorduser',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twitcorduser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='twitcorduser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='twitcorduser',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
