# Generated by Django 3.1.7 on 2021-05-04 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitcord_app', '0005_auto_20210503_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='twitcord_app.tweet'),
        ),
        migrations.AlterField(
            model_name='userfollowing',
            name='type',
            field=models.CharField(choices=[('family', 'family'), ('friend', 'friend'), ('close friend', 'close friend'), ('celebrity', 'celebrity'), ('unfamiliar person', 'unfamiliar person')], default='unfamiliar person', max_length=30),
        ),
    ]
