# Generated by Django 3.1.7 on 2021-05-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitcord_app', '0009_auto_20210521_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollowing',
            name='type',
            field=models.CharField(choices=[('FA', 'family'), ('FR', 'friend'), ('CF', 'close friend'), ('CL', 'celebrity'), ('UP', 'unfamiliar person')], default='UP', max_length=30),
        ),
    ]
