# Generated by Django 3.1.7 on 2021-05-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitcord_app', '0011_auto_20210521_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollowing',
            name='type',
            field=models.CharField(choices=[('Family', 'family'), ('Friend', 'friend'), ('Close_friend', 'close friend'), ('Unfamiliar_person', 'unfamiliar person')], default='Unfamiliar_person', max_length=30),
        ),
    ]
