# Generated by Django 3.1.7 on 2021-05-27 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitcord_app', '0012_auto_20210521_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='retweet_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retweet_of', to='twitcord_app.tweet'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_to', to='twitcord_app.tweet'),
        ),
        migrations.AddConstraint(
            model_name='tweet',
            constraint=models.CheckConstraint(check=models.Q(('retweet_from__isnull', True), ('content__isnull', False)), name='content_null'),
        ),
    ]
