# Generated by Django 3.1.7 on 2021-06-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitcord_app', '0019_profile_header_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(max_length=280, null=True),
        ),
    ]
