# Generated by Django 3.1.7 on 2021-06-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitcord_app', '0021_tweet_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
    ]
