# Generated by Django 3.1.7 on 2021-06-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitcord_app', '0022_room_image'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tweet',
            constraint=models.UniqueConstraint(condition=models.Q(content__isnull=True), fields=('user', 'retweet_from'), name='unique_retweet'),
        ),
    ]
